
package webservice.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestGenService", targetNamespace = "http://appws/", wsdlLocation = "http://127.0.0.1:7101/AppWS/TestGenPort?WSDL#%7Bhttp%3A%2F%2Fappws%2F%7DTestGenService")
public class TestGenService
    extends Service
{

    private final static URL TESTGENSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.proxy.TestGenService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.proxy.TestGenService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:7101/AppWS/TestGenPort?WSDL#%7Bhttp%3A%2F%2Fappws%2F%7DTestGenService");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:7101/AppWS/TestGenPort?WSDL#%7Bhttp%3A%2F%2Fappws%2F%7DTestGenService', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTGENSERVICE_WSDL_LOCATION = url;
    }

    public TestGenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestGenService() {
        super(TESTGENSERVICE_WSDL_LOCATION, new QName("http://appws/", "TestGenService"));
    }

    /**
     * 
     * @return
     *     returns TestGen
     */
    @WebEndpoint(name = "TestGenPort")
    public TestGen getTestGenPort() {
        return super.getPort(new QName("http://appws/", "TestGenPort"), TestGen.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestGen
     */
    @WebEndpoint(name = "TestGenPort")
    public TestGen getTestGenPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://appws/", "TestGenPort"), TestGen.class, features);
    }

}
