
package webservice.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import webservice.proxy.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TestGen", targetNamespace = "http://appws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestGen {


    /**
     * 
     * @param activityDiagramFile
     * @param templateFile
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://appws/")
    @RequestWrapper(localName = "generarActivityDiagram", targetNamespace = "http://appws/", className = "webservice.proxy.types.GenerarActivityDiagram")
    @ResponseWrapper(localName = "generarActivityDiagramResponse", targetNamespace = "http://appws/", className = "webservice.proxy.types.GenerarActivityDiagramResponse")
    public String generarActivityDiagram(
        @WebParam(name = "templateFile", targetNamespace = "http://appws/")
        String templateFile,
        @WebParam(name = "activityDiagramFile", targetNamespace = "http://appws/")
        String activityDiagramFile);

    /**
     * 
     * @param templateFile
     * @param testObjectiveFile
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://appws/")
    @RequestWrapper(localName = "generarSecuencias", targetNamespace = "http://appws/", className = "webservice.proxy.types.GenerarSecuencias")
    @ResponseWrapper(localName = "generarSecuenciasResponse", targetNamespace = "http://appws/", className = "webservice.proxy.types.GenerarSecuenciasResponse")
    public String generarSecuencias(
        @WebParam(name = "templateFile", targetNamespace = "http://appws/")
        String templateFile,
        @WebParam(name = "testObjectiveFile", targetNamespace = "http://appws/")
        String testObjectiveFile);

}
