package webservice.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.0.0.6017

public class TestGenPortClient
{
  public static void main(String [] args)
  {
    TestGenService testGenService = new TestGenService();
    TestGen testGen = testGenService.getTestGenPort();
    // Add your code to call the desired methods.
  }
}
