package webservice.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 23 13:32:53 PYST 2011
// ---------------------------------------------------------------------
public interface AppMoWebService extends ApplicationModule {
    String WSGenerarActivityDiagram(String templateDir, String activityDiagramDir);

    String WSGenerarSecuencias(String templateDir, String testObjectiveFile);
}
