package model;

import model.view.FlujoAlternativoViewImpl;
import model.view.FlujoBasicoViewImpl;

import model.view.FlujoErrorViewImpl;

import model.view.ValoresDeParametrosViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 15 15:26:20 PYST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppMoGenCPImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppMoGenCPImpl() {
    }

    /**
     * Container's getter for FlujoBasicoView1.
     * @return FlujoBasicoView1
     */
    public FlujoBasicoViewImpl getFlujoBasicoView1() {
        return (FlujoBasicoViewImpl)findViewObject("FlujoBasicoView1");
    }

    /**
     * Container's getter for FlujoAlternativoView1.
     * @return FlujoAlternativoView1
     */
    public FlujoAlternativoViewImpl getFlujoAlternativoView1() {
        return (FlujoAlternativoViewImpl)findViewObject("FlujoAlternativoView1");
    }

    /**
     * Container's getter for FlujoErrorView1.
     * @return FlujoErrorView1
     */
    public FlujoErrorViewImpl getFlujoErrorView1() {
        return (FlujoErrorViewImpl)findViewObject("FlujoErrorView1");
    }

    /**
     * Container's getter for ValoresDeParametrosView1.
     * @return ValoresDeParametrosView1
     */
    public ValoresDeParametrosViewImpl getValoresDeParametrosView1() {
        return (ValoresDeParametrosViewImpl)findViewObject("ValoresDeParametrosView1");
    }
}
