// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
package appws;


public class GenerarSecuenciasResponse implements java.io.Serializable {
    protected java.lang.String _return;
    
    public GenerarSecuenciasResponse() {
    }
    
    public java.lang.String get_return() {
        return _return;
    }
    
    public void set_return(java.lang.String _return) {
        this._return = _return;
    }
}
