// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
package appws;


public class GenerarActivityDiagram implements java.io.Serializable {
    protected java.lang.String templateFile;
    protected java.lang.String activityDiagramFile;
    
    public GenerarActivityDiagram() {
    }
    
    public java.lang.String getTemplateFile() {
        return templateFile;
    }
    
    public void setTemplateFile(java.lang.String templateFile) {
        this.templateFile = templateFile;
    }
    
    public java.lang.String getActivityDiagramFile() {
        return activityDiagramFile;
    }
    
    public void setActivityDiagramFile(java.lang.String activityDiagramFile) {
        this.activityDiagramFile = activityDiagramFile;
    }
}
