package webservice.client;

import webservice.common.AppMoWebService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 23 13:32:53 PYST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppMoWebServiceClient extends ApplicationModuleImpl implements AppMoWebService {
    /**
     * This is the default constructor (do not remove).
     */
    public AppMoWebServiceClient() {
    }


    public String WSGenerarSecuencias(String templateDir) {
        Object _ret = this.riInvokeExportedMethod(this,"WSGenerarSecuencias",new String [] {"java.lang.String"},new Object[] {templateDir});
        return (String)_ret;
    }

    public String WSGenerarActivityDiagram(String templateDir, String activityDiagramDir) {
        Object _ret =
            this.riInvokeExportedMethod(this,"WSGenerarActivityDiagram",new String [] {"java.lang.String","java.lang.String"},new Object[] {templateDir, activityDiagramDir});
        return (String)_ret;
    }

    public String WSGenerarSecuencias(String templateDir, String testObjectiveFile) {
        Object _ret =
            this.riInvokeExportedMethod(this,"WSGenerarSecuencias",new String [] {"java.lang.String","java.lang.String"},new Object[] {templateDir, testObjectiveFile});
        return (String)_ret;
    }
}
